apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    name: web-server
spec:
  containers:
  - name: web-server
    image: my-nginx 
    imagePullPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
