kind: Service
apiVersion: v1
metadata:
  name:  for-rust-back
spec:
  selector:
    name:  rust-back
  type:  ClusterIP
  clusterIP: 10.96.80.80
  ports:
  - name:  rust-back
    port:  80
    targetPort:  8081