apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web-server-deployment
  labels:
    name:  web-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name:  web-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  web-server
    spec:
      containers:
      - image:  ipedrazas/docmock
        name:  my-nginx
        resources:
          requests:
            cpu: "20m"
            memory: "55M"